### PR TITLE
container_create: fix dev mounts and remove nodev from every mount

### LINKED ISSUE #1881: Bind mount for /dev not handled correctly
After passing host /dev as a volume to a container, I was seeing issues accessing certain devices within the container. Inspecting the config.json for the container, revealed that two mounts had been added with destination /dev.
```
 {
                        "destination": "/dev",
                        "type": "tmpfs",
                        "source": "tmpfs",
                        "options": [
                                "nosuid",
                                "strictatime",
                                "mode=755",
                                "size=65536k"
                        ]
},
...
 {
                        "destination": "/dev",
                        "type": "bind",
                        "source": "/dev",
                        "options": [
                                "rw",
                                "rbind",
                                "nodev",
                                "rprivate",
                                "bind"
                        ]
},
```
Shouldn't the config.json just contain the second bind mount?

### PR DESCRIPTION
**Pull request by runcom**
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

**- What I did**

- fix #1881 
- made sure we don't add mounts in /dev where not needed
- removed nodev from every mount (I don't even remember why we did that but doesn't look right and could have caused the recent issues in kata as well

**- How I did it**

vi

**- How to verify it**

the kata job in the CI should cover this scenario and if it passes, then it's verified.

**- Description for the changelog**

### CODE REVIEW

**Comment by runcom** [comment]
@chavafg take a look please, I suspect this is gonna take care of https://github.com/kubernetes-sigs/cri-o/issues/1881 and https://github.com/kubernetes-sigs/cri-o/issues/1883

**Comment by runcom** [comment]
@mrunalp PTAL

**Comment by runcom** [comment]
we'll need this in 1.12 as well

**Comment by runcom** [comment]
unfortunately kata job is enqueued and it's gonna take some time to be kicked for this PR. @chavafg are you able to manually test this? @amshinde would you also try and verify this? Thanks a lot guys

**Comment by runcom** [comment]
@chavafg can you see if kata fails because of dev stuff?

**Comment by chavafg** [comment]
@runcom yes, still failing because of the same issue. 
I took a look at #1700 where we had similar issues and @rhatdan seem to solved the issue using this: https://github.com/kubernetes-sigs/cri-o/pull/1700/files#diff-2b41f932adaaa89de8a9d3d2ab660a49R423
but at the end his PR didnt get merged.

File: server/container_create_linux.go [hunk 1]
```diff
@@ -1008,7 +1035,7 @@ func addOCIBindMounts(mountLabel string, containerConfig *pb.ContainerConfig, sp
 		if mount.Readonly {
 			options = []string{"ro"}
 		}
-		options = append(options, "rbind", "nodev")
+		options = append(options, "rbind")
```
Comment (rhatdan) [inline server/container_create_linux.go]: I think you want nodev to be everywhere except if the mountpoint is from /dev.  But I think this is too big of a hammer.
@umohnani8 Did you add this?

Comment (runcom) [reply server/container_create_linux.go]: it's indeed to big, I've see nodev only in tmpfs mount in docker for instance. I don't know why we would add it everywhere

**Comment by runcom** [comment]
> @runcom yes, still failing because of the same issue.
> I took a look at #1700 where we had similar issues and @rhatdan seem to solved the issue using this: https://github.com/kubernetes-sigs/cri-o/pull/1700/files#diff-2b41f932adaaa89de8a9d3d2ab660a49R423
> but at the end his PR didnt get merged.

alright, so it's actually containers/storage @nalind @rhatdan @mrunalp

File: server/container_create_linux.go (hunk 1 above)
Comment (umohnani8) [reply server/container_create_linux.go]: Yeah I did, it was to fix the issue reported in this BZ https://bugzilla.redhat.com/show_bug.cgi?id=1627633.

**Comment by runcom** [comment]
@chavafg I'm not sure BTW, there must have been a regression though. The PR you linked is pretty old so either Kata was broken with cri-o for so long or it did break recently right?

File: server/container_create_linux.go (hunk 1 above)
Comment (umohnani8) [reply server/container_create_linux.go]: So this should be reverted to keep "nodev" there right?

Comment (runcom) [reply server/container_create_linux.go]: most likely, yeah, I'll will do that in a bit

Comment (runcom) [reply server/container_create_linux.go]: see https://github.com/kubernetes-sigs/cri-o/pull/1884/files#diff-aab4c88107335f18845d9e317503a02dR1040

we now add `nodev` if and only if the mount destination is not under `/dev/` (which would defeat the whole dev mount otherwise)

**Comment by chavafg** [comment]
Hi @runcom, taking a look today. 
I think it is not only kata specific. I could reproduce the issue on runc.

**Comment by runcom** [comment]
@chavafg if you could bisect and understand if it's a regression that would help. If you can reproduce with runc, I could run the bisect as well

**Comment by runcom** [comment]
creating an integration test for this also

File: server/container_create_linux.go [hunk 2]
```diff
@@ -1008,7 +1035,11 @@ func addOCIBindMounts(mountLabel string, containerConfig *pb.ContainerConfig, sp
...
+
+		if !strings.HasPrefix(dest, "/dev") {
+			options = append(options, "nodev")
```
Comment (giuseppe) [inline server/container_create_linux.go]: do we want a way to override the `nodev` if required? e.g. should it be added if there is already an explicit `dev` option?

Comment (runcom) [reply server/container_create_linux.go]: mount takes the last option and applies nodev as a result (talked to Giuseppe on IRC)
